export const LIST_EXPENSES = [
    "Accountant",
    "Advertising",
    "Auto expenses",
    "Bad Debts",
    "Business licenses",
    "Business supplies",
    "Business taxes",
    "Casualty and theft",
    "Charitable Contributions",
    "Educational Expenses",
    "Entertainment",
    "Financial institution fees",
    "Labor",
    "Moving Expenses",
    "Postage and shipping fees",
    "Professional fees",
    "Rent",
    "Repairs",
    "Software",
    "Taxes",
    "Telecom",
    "Travel expenses",
    "Utilities"
];